inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - spec/dummy/**/*
    - vendor/**/*
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Lint/UnusedMethodArgument:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MessageChain:
  Enabled: false

Style/ClassVars:
  Enabled: false
