default: &default
  database: database_recorder
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgresql' } %>
  host: <%= ENV.fetch('DB_HOST') { '127.0.0.1' } %>
  username: <%= ENV.fetch('DB_USERNAME') { '' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') { 'database_recorder-test' } %>
