---
name: Specs ActiveRecord

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  specs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0']

    env:
      DB_ADAPTER: active_record
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: database_recorder-test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup DB
        run: cd spec/dummy && RAILS_ENV=test bundle exec rails db:create db:migrate

      - name: Run tests
        run: bundle exec rspec
